/**
 * Metric Registry — single source of truth for every dashboard metric.
 * Pure data file — no Supabase imports, no async, no side effects.
 */

export type MetricSpec = {
  id: string;
  name: string;
  formula: string;
  sourceTables: string[];
  window: '1d' | '7d' | '30d' | 'file';
  warnThreshold?: number;
  criticalThreshold?: number;
  thresholdDirection?: 'above' | 'below'; // 'above' = bad if above, 'below' = bad if below
  interpretation: string; // "Up is good" / "Down is good" / plain English
  owner: 'ops' | 'pm' | 'eng';
  isNew?: boolean; // true for Phase 9 additions
};

export const METRIC_REGISTRY: MetricSpec[] = [
  // ─── Volume / Summary Metrics ──────────────────────────────────────────────
  {
    id: 'total_conversations',
    name: 'Total Conversations',
    formula: 'COUNT(conversation_sessions WHERE last_activity >= since)',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    interpretation: 'Total number of unique chat sessions started in the period. Up is good (more usage).',
    owner: 'ops',
  },
  {
    id: 'total_leads',
    name: 'Total Leads',
    formula: 'COUNT(leads WHERE created_at >= since)',
    sourceTables: ['leads'],
    window: '7d',
    interpretation: 'Maid hire inquiries that reached escalation (all 4 required fields collected). Up is good.',
    owner: 'pm',
  },
  {
    id: 'total_complaints',
    name: 'Total Complaints',
    formula: 'COUNT(complaints WHERE created_at >= since)',
    sourceTables: ['complaints'],
    window: '7d',
    interpretation: 'Complaint sessions escalated to the support team. Down is good.',
    owner: 'ops',
  },
  {
    id: 'total_maid_registrations',
    name: 'Total Helper Registrations',
    formula: 'COUNT(maid_registrationistrations WHERE created_at >= since)',
    sourceTables: ['maid_registrationistrations'],
    window: '7d',
    interpretation: 'Helper registration inquiries escalated. Up is good (supply side).',
    owner: 'pm',
  },

  // ─── Latency Metrics ───────────────────────────────────────────────────────
  {
    id: 'avg_latency_ms',
    name: 'Average Response Latency',
    formula: 'AVG(llm_logs.took_ms WHERE created_at >= since)',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 5000,
    criticalThreshold: 10000,
    thresholdDirection: 'above',
    interpretation: 'Average time (ms) from user message to bot response. Down is good.',
    owner: 'eng',
  },
  {
    id: 'p50_latency_ms',
    name: 'P50 Response Latency',
    formula: 'PERCENTILE(llm_logs.took_ms, 50) WHERE created_at >= since',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 4000,
    thresholdDirection: 'above',
    interpretation: 'Median response time (ms) — half of users wait less than this. Down is good.',
    owner: 'eng',
  },
  {
    id: 'p95_latency_ms',
    name: 'P95 Response Latency',
    formula: 'PERCENTILE(llm_logs.took_ms, 95) WHERE created_at >= since',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 8000,
    criticalThreshold: 15000,
    thresholdDirection: 'above',
    interpretation: 'Tail response time (ms) — 95% of users wait less than this. Down is good.',
    owner: 'eng',
  },

  // ─── Error / Reliability Metrics ───────────────────────────────────────────
  {
    id: 'safety_net_trigger_rate',
    name: 'Safety Net Trigger Rate',
    formula: 'safetyNetTriggers / total * 100 — turns where raw_llm_response == "." or trim().length < 4',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 5,
    criticalThreshold: 10,
    thresholdDirection: 'above',
    interpretation: 'Percentage of LLM turns where the response was empty or near-empty, triggering the safety net fallback. Down is good.',
    owner: 'eng',
  },
  {
    id: 'guardrail_mod_rate',
    name: 'Guardrail Modification Rate',
    formula: 'guardrailModified / total * 100 — turns where raw_llm_response !== after_guardrails',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 20,
    thresholdDirection: 'above',
    interpretation: 'Percentage of turns where guardrails altered the LLM response (price stripped, phone validated, links removed). High values indicate the LLM is violating its prompt instructions. Down is good.',
    owner: 'eng',
  },

  // ─── Lead / Product Health Metrics ─────────────────────────────────────────
  {
    id: 'lead_completion_rate',
    name: 'Lead Completion Rate',
    formula: 'completed_sessions / total_maid_hire_sessions * 100 (current_state == "COMPLETE")',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 50,
    thresholdDirection: 'below',
    interpretation: 'Percentage of maid hire conversations that reached the COMPLETE state. Up is good.',
    owner: 'pm',
  },
  {
    id: 'lead_quality_score',
    name: 'Lead Quality Score',
    formula: '(avg non-skipped fields per completed lead / 7 total fields) * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 70,
    thresholdDirection: 'below',
    interpretation: 'Average completeness of collected lead data (0–100). A score of 100 means all 7 fields filled. Up is good.',
    owner: 'pm',
  },
  {
    id: 'effective_escalation_rate',
    name: 'Effective Escalation Rate',
    formula: 'sessions_with_all_4_required_fields / total_maid_hire_sessions * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 40,
    thresholdDirection: 'below',
    interpretation: 'Percentage of sessions that collected all 4 required fields (phone, location, service_type, schedule) before escalating. Up is good.',
    owner: 'pm',
  },
  {
    id: 'recovery_rate',
    name: 'Recovery Rate',
    formula: 'sessions_that_recovered (attempts>0 AND COMPLETE) / sessions_with_retries (attempts>0) * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 50,
    thresholdDirection: 'below',
    interpretation: 'Percentage of sessions that experienced a validation failure but eventually reached COMPLETE. Up is good — the bot is recovering from user input errors.',
    owner: 'pm',
  },
  {
    id: 'abandonment_rate',
    name: 'Abandonment Rate',
    formula: 'sessions_inactive_over_1h_not_completed / total_sessions * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 30,
    criticalThreshold: 50,
    thresholdDirection: 'above',
    interpretation: 'Percentage of sessions that were abandoned (inactive > 1h without completing). Down is good.',
    owner: 'pm',
  },
  {
    id: 'avg_session_duration_ms',
    name: 'Average Session Duration',
    formula: 'AVG(last_activity - created_at) for sessions with duration < 24h',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    interpretation: 'Average time (ms) from session start to last activity. Shorter duration for completed sessions is better.',
    owner: 'pm',
  },

  // ─── Response Quality Metrics ──────────────────────────────────────────────
  {
    id: 'keyword_fallback_rate',
    name: 'Keyword Fallback Rate',
    formula: 'turns_where_after_guardrails_length > raw_length + 20 / total_turns * 100',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 15,
    thresholdDirection: 'above',
    interpretation: 'Percentage of turns where the keyword fallback appended the step question (LLM failed to ask the right question). Down is good.',
    owner: 'eng',
  },

  // ─── Shadow / Alignment Metrics ───────────────────────────────────────────
  {
    id: 'shadow_alignment_rate',
    name: 'Shadow Alignment Rate',
    formula: 'agreed_logs / total_shadow_logs * 100',
    sourceTables: ['shadow_logs'],
    window: '7d',
    warnThreshold: 95,
    thresholdDirection: 'below',
    interpretation: 'Percentage of turns where the agentic LLM shadow agreed with the deterministic state machine. >= 95% for 7 consecutive days is the go-live gate. Up is good.',
    owner: 'eng',
  },

  // ─── Eval Track Scores ────────────────────────────────────────────────────
  {
    id: 'eval_state_score',
    name: 'Eval: State Machine Score',
    formula: 'overallScore from latest eval-state-*.json file',
    sourceTables: [],
    window: 'file',
    warnThreshold: 90,
    criticalThreshold: 80,
    thresholdDirection: 'below',
    interpretation: 'Pass rate (%) from the state machine golden dataset evaluation. >= 90% = Production Ready. Up is good.',
    owner: 'eng',
  },
  {
    id: 'eval_unhappy_score',
    name: 'Eval: Unhappy Path Score',
    formula: 'overallScore from latest eval-unhappy-*.json file',
    sourceTables: [],
    window: 'file',
    warnThreshold: 90,
    criticalThreshold: 80,
    thresholdDirection: 'below',
    interpretation: 'Pass rate (%) from the unhappy path golden dataset evaluation (edge cases, gibberish, off-topic). >= 90% = Production Ready. Up is good.',
    owner: 'eng',
  },

  // ─── NEW Phase 9 Agentic Quality Metrics (isNew: true) ────────────────────

  {
    id: 'stuck_loop_rate',
    name: 'Stuck Loop Rate',
    formula: 'sessions_with_attempts >= 3 / total_maid_hire_sessions * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 5,
    criticalThreshold: 15,
    thresholdDirection: 'above',
    interpretation: 'Percentage of sessions where the bot got stuck (3+ failed attempts). Proxy for bot confusion loops. Down is good.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'escalation_after_confusion_rate',
    name: 'Escalation After Confusion Rate',
    formula: 'sessions_with_attempts > 2 AND current_state == "COMPLETE" / sessions_with_attempts > 0 * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 20,
    thresholdDirection: 'above',
    interpretation: 'Percentage of sessions that eventually completed despite having > 2 failed attempts. High values indicate the bot is recovering from confusion — neutral signal.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'slot_retention_after_switch',
    name: 'Slot Retention After Intent Switch',
    formula: 'sessions_with___intent_stack_AND_COMPLETE / sessions_with___intent_stack * 100. Returns -1 if no multi-intent sessions detected.',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 80,
    thresholdDirection: 'below',
    interpretation: 'Percentage of sessions that preserved previously collected slots after an intent switch. Up is good. -1 means no multi-intent sessions in the period.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'ambiguity_resolution_rate',
    name: 'Ambiguity Resolution Rate',
    formula: 'sessions_with_attempts > 0 AND COMPLETE / sessions_with_attempts > 0 * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 60,
    thresholdDirection: 'below',
    interpretation: 'Percentage of sessions that had at least one validation failure but ultimately resolved to COMPLETE. Up is good.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'resume_success_rate',
    name: 'Resume Success Rate',
    formula: 'sessions_where_prior_slots_intact_after_resume / total_resumes * 100. Proxy: same as slot_retention_after_switch until multi-intent tracking is live.',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 80,
    thresholdDirection: 'below',
    interpretation: 'Percentage of session resumes where previously collected data was preserved. Up is good. -1 means no resume events in the period.',
    owner: 'eng',
    isNew: true,
  },
  {
    id: 'intent_switch_success_rate',
    name: 'Intent Switch Success Rate',
    formula: 'successful_resumes / total_intent_switches * 100. Proxy: slot_retention_after_switch until __intent_stack tracking matures.',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 80,
    thresholdDirection: 'below',
    interpretation: 'Percentage of intent switches where the bot correctly resumed the prior flow. Up is good. -1 means no intent switch sessions in the period.',
    owner: 'eng',
    isNew: true,
  },
  {
    id: 'memory_retention_rate',
    name: 'Memory Retention Rate',
    formula: 'Alias for resume_success_rate — slots preserved after intent switch',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 80,
    thresholdDirection: 'below',
    interpretation: 'Alias for Resume Success Rate. Measures whether the bot remembers collected data across topic switches. Up is good.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'repeat_question_rate',
    name: 'Repeat Question Rate',
    formula: 'turns_where_raw_llm_response_first_60_chars_matches_prior_turn_in_same_conversation / total_turns * 100',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 5,
    criticalThreshold: 10,
    thresholdDirection: 'above',
    interpretation: 'Percentage of turns where the bot asked the same question it already asked (verbatim prefix match). Down is good — indicates the bot is losing track of conversation state.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'guardrail_bypass_attempt_rate',
    name: 'Guardrail Bypass Attempt Rate',
    formula: 'turns_where_raw_llm_response !== after_guardrails / total_maid_hire_turns * 100',
    sourceTables: ['llm_logs'],
    window: '7d',
    warnThreshold: 10,
    criticalThreshold: 25,
    thresholdDirection: 'above',
    interpretation: 'Percentage of maid_hire turns where guardrails modified the LLM output. Scoped to maid_hire intent. Down is good.',
    owner: 'eng',
    isNew: true,
  },
  {
    id: 'semantic_paraphrase_success',
    name: 'Semantic Paraphrase Success Rate',
    formula: 'recovery_turns_that_resolved / rephrase_attempts (attempts>1 per slot) * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 70,
    thresholdDirection: 'below',
    interpretation: 'Percentage of validation retries (attempts > 1 for a slot) that eventually succeeded. Up is good.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'intent_drift_rate',
    name: 'Intent Drift Rate',
    formula: 'sessions where detected_intent="maid_hire" AND current_state="START" AND attempts=0 after first message / total_sessions * 100',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    warnThreshold: 10,
    thresholdDirection: 'above',
    interpretation: 'Proxy for sessions that were classified as maid_hire but never progressed. Indicates intent misclassification or early abandonment. Down is good.',
    owner: 'eng',
    isNew: true,
  },
  {
    id: 'hallucination_rate',
    name: 'Hallucination Rate (HITL)',
    formula: 'human_labeled_hallucination_turns / sampled_turns * 100 — HITL metric, not automated',
    sourceTables: ['llm_logs'],
    window: '7d',
    interpretation: 'Percentage of sampled turns labeled by a human reviewer as containing fabricated information. Requires manual sampling. Down is good. NOTE: data collection is not automated.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'human_handoff_completion_rate',
    name: 'Human Handoff Completion Rate',
    formula: 'sessions_reaching_COMPLETE_with_escalation / total_escalated_sessions * 100',
    sourceTables: ['leads', 'conversation_sessions'],
    window: '7d',
    warnThreshold: 70,
    thresholdDirection: 'below',
    interpretation: 'Percentage of escalated sessions that completed the full lead capture flow. Up is good.',
    owner: 'pm',
    isNew: true,
  },
  {
    id: 'slot_retry_distribution',
    name: 'Slot Retry Distribution',
    formula: 'per-field retry counts from conversation_sessions.attempts',
    sourceTables: ['conversation_sessions'],
    window: '7d',
    interpretation: 'Breakdown of validation retries per slot field. High retry counts on specific fields indicate prompt or validation issues.',
    owner: 'eng',
    isNew: true,
  },
  {
    id: 'recovery_step_distribution',
    name: 'Recovery Step Distribution',
    formula: 'clarify / reframe / escalate counts from llm_logs.system_prompt keyword analysis',
    sourceTables: ['llm_logs'],
    window: '7d',
    interpretation: 'Breakdown of recovery strategy used per confused turn (clarify, reframe, escalate). Informs prompt tuning.',
    owner: 'eng',
    isNew: true,
  },
];

/**
 * Look up a metric definition by its ID.
 */
export function getMetricSpec(id: string): MetricSpec | undefined {
  return METRIC_REGISTRY.find(m => m.id === id);
}
